# Generated by Django 2.1.3 on 2018-11-26 20:47

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(null=True, upload_to='pho/%Y/%m/%d/')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('uploader', models.CharField(editable=False, max_length=200, verbose_name='上傳者')),
            ],
        ),
    ]
