# Generated by Django 2.1.2 on 2018-11-03 11:34

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', stdimage.models.StdImageField(blank=True, upload_to='pho/%Y/%M/%D/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
