# Generated by Django 2.1.2 on 2018-11-03 11:36

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=stdimage.models.StdImageField(null=True, upload_to='pho/%Y/%m/%d/'),
        ),
    ]
