# Generated by Django 2.1.2 on 2018-10-28 13:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20181028_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, upload_to='pho/%Y/%M/%D/'),
        ),
    ]
