# Generated by Django 2.1.3 on 2018-11-20 11:55

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(default='陌生人', max_length=30, verbose_name='留言的人')),
                ('context', models.TextField(max_length=140, verbose_name='留言內容')),
                ('post_time', models.DateTimeField(auto_now_add=True, verbose_name='留言時間')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='網址')),
                ('context', models.TextField(verbose_name='文章內容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('edited_time', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('image', models.ImageField(blank=True, upload_to=blog.models.Post.rename, verbose_name='側邊圖片')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
