# Generated by Django 2.1.3 on 2018-11-12 18:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.Post.rename, verbose_name='側邊圖片'),
        ),
    ]
