# Generated by Django 2.1.3 on 2018-11-26 20:47

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to=blog.models.Post.rename, verbose_name='側邊圖片'),
        ),
    ]
