# Generated by Django 2.1.3 on 2018-12-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181209_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
    ]
