# Generated by Django 2.1.2 on 2018-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, verbose_name='首頁圖片'),
        ),
    ]
