# Generated by Django 2.1.2 on 2018-10-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181012_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改時間'),
        ),
    ]
