# Generated by Django 2.1.2 on 2018-10-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181012_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=10, verbose_name='留言的人')),
                ('post_time', models.DateTimeField(auto_now=True, verbose_name='留言時間')),
                ('comment', models.TextField(max_length=150)),
                ('which_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
