# Generated by Django 2.1.2 on 2018-10-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_edited_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post/side', verbose_name='側邊圖片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='發布時間'),
        ),
    ]
