# Generated by Django 2.1.2 on 2018-10-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-post_time',)},
        ),
    ]
