# Generated by Django 2.1.2 on 2018-11-03 10:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181028_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.Post.rename, verbose_name='側邊圖片'),
        ),
    ]
