# Generated by Django 2.1.2 on 2018-10-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181014_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-post_time',)},
        ),
    ]
